### PR TITLE
New node logic

### PR DESCRIPTION
**Pull request by PavelBlend**
I redid the logic of collecting information from nodes. Fixed errors in the organization of the code.
And most importantly, what it gave is the ability to load an arbitrary cache in this way (using a single node):

To create a mesh and particle system, you need these nodes:

### CODE REVIEW

**Comment by PavelBlend** [comment]
In general, in a blender, the nodes of the node system are output nodes. I was the main Simulate node in our system (and this is not correct, since it is not an output node).
And further:
The simulate button has been moved to the title bar of the node window.

**Comment by yuanming-hu** [comment]
Great! If I understand correctly, the `particle_mesh` node is for caching the meshes used as geometry for particle seeding?

> The simulate button has been moved to the title bar of the node window.

Cool! It looks good to have `simulate` together with `render` :-)

**Comment by PavelBlend** [comment]
> If I understand correctly, the `particle_mesh` node is for caching the meshes used as geometry for particle seeding?

no. To save particles to the cache, the Disk Cache node is used. And the Particle Mesh node only imports particle data from the cache into the scene in the form of an object mesh (which has only vertices). And the particle system node imports data from the cache as a standard particle blender system.

That is, the particle mesh node and the particle system node simply import data from the already baked cache. And these nodes can work without other nodes. That is, they can be alone and import any cache from another scene.

**Comment by yuanming-hu** [comment]
I see. Thanks for the explanation. I didn't realize we only use the vertices of a `particle mesh` :-)

**Pull request merged**
