### PR TITLE
Static sphere colliders with three types of surfaces

### PR DESCRIPTION
**Pull request by yuanming-hu**
#17 

Demo: https://youtu.be/A2yuWoXCy58

### CODE REVIEW

**Comment by PavelBlend** [comment]
My demo_3d_collider.py is working with an error. The window is closing.
```
[Taichi] mode=release
[Taichi] version 0.5.10, cpu only, commit 58761902, python 3.8.1
[W 04/10/20 17:41:18.388] [program.cpp:taichi::lang::Program::Program@40] Taichi is not compiled with CUDA.
[W 04/10/20 17:41:18.389] [program.cpp:taichi::lang::Program::Program@63] Falling back to x64
[E 04/10/20 17:42:30.877] Received signal 11 (SIGSEGV)
```

**Comment by yuanming-hu** [comment]
Let me see. One sec.

**Comment by yuanming-hu** [comment]
What's your operating system? I'm on Linux and I failed to reproduce the crash...

**Comment by PavelBlend** [comment]
Windows 10 64 bit

**Comment by yuanming-hu** [comment]
Thanks for the info - I reboot into Windows 10 64bit and I can reproduce this issue now. Let me see if I can fix it quickly.

**Comment by yuanming-hu** [comment]
Unfortunately, this seems a convoluted bug to fix - I have to switch to my work now, and I'll have more time during the weekend to fix this.  Sorry about that! I'll try to fix it tomorrow.

**Comment by PavelBlend** [comment]
No problem.

**Comment by yuanming-hu** [comment]
The Windows issues should be resolved in taichi v0.5.11. The buildbots are building the Windows releases now.  If nothing goes wrong, you should be able to install `taichi-nightly==v0.5.11` in two hours. 

I have to sleep now... See you online tomorrow! :-)

**Pull request merged**
